// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SerializeOptions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from SerializeOptions.proto</summary>
public static partial class SerializeOptionsReflection {

  #region Descriptor
  /// <summary>File descriptor for SerializeOptions.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SerializeOptionsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChZTZXJpYWxpemVPcHRpb25zLnByb3RvGiBnb29nbGUvcHJvdG9idWYvZGVz",
          "Y3JpcHRvci5wcm90byo2Cg1SZXBlYXRlZENsYXNzEgoKBlJDTGlzdBAAEg0K",
          "CVJjSGFzaFNldBABEgoKBlJjRGljdBACKlgKCVJjRGljdEtleRIQCgxSY0Rp",
          "Y3RLZXlJbnQQABIRCg1SY0RpY3RLZXlMb25nEAESEwoPUmNEaWN0S2V5U3Ry",
          "aW5nEAISEQoNUmNEaWN0S2V5VHlwZRADKhYKCE1hcENsYXNzEgoKBk1jRGlj",
          "dBAAOjIKCnNvX25zX2Jhc2USHC5nb29nbGUucHJvdG9idWYuRmlsZU9wdGlv",
          "bnMY0IYDIAEoCTozCghzb19jbGFzcxIfLmdvb2dsZS5wcm90b2J1Zi5NZXNz",
          "YWdlT3B0aW9ucxjRhgMgASgJOkoKEXNvX3JlcGVhdGVkX2NsYXNzEh0uZ29v",
          "Z2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjShgMgASgOMg4uUmVwZWF0ZWRD",
          "bGFzczpHChJzb19yY2RpY3Rfa2V5X3R5cGUSHS5nb29nbGUucHJvdG9idWYu",
          "RmllbGRPcHRpb25zGNOGAyABKA4yCi5SY0RpY3RLZXk6OwoSc29fcmNkaWN0",
          "X2tleV9uYW1lEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjUhgMg",
          "ASgJOkAKDHNvX21hcF9jbGFzcxIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9w",
          "dGlvbnMY1YYDIAEoDjIJLk1hcENsYXNzOjgKD3NvX2N1c3RvbV9maWVsZBId",
          "Lmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMY1oYDIAEoCA=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::RepeatedClass), typeof(global::RcDictKey), typeof(global::MapClass), }, new pb::Extension[] { SerializeOptionsExtensions.SoNsBase, SerializeOptionsExtensions.SoClass, SerializeOptionsExtensions.SoRepeatedClass, SerializeOptionsExtensions.SoRcdictKeyType, SerializeOptionsExtensions.SoRcdictKeyName, SerializeOptionsExtensions.SoMapClass, SerializeOptionsExtensions.SoCustomField }, null));
  }
  #endregion

}
/// <summary>Holder for extension identifiers generated from the top level of SerializeOptions.proto</summary>
public static partial class SerializeOptionsExtensions {
  /// <summary>
  /// 指定基础的命名空间
  /// </summary>
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FileOptions, string> SoNsBase =
    new pb::Extension<global::Google.Protobuf.Reflection.FileOptions, string>(50000, pb::FieldCodec.ForString(400002, ""));
  /// <summary>
  /// 指定对应的C#类，co_ns_base.co_class 得到类全名
  /// 如果不指定且消息以Pb开头，则默认类名为去掉Pb的名字
  /// </summary>
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string> SoClass =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string>(50001, pb::FieldCodec.ForString(400010, ""));
  /// <summary>
  /// repeated对应的C#类
  /// </summary>
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::RepeatedClass> SoRepeatedClass =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::RepeatedClass>(50002, pb::FieldCodec.ForEnum(400016, x => (int) x, x => (global::RepeatedClass) x, global::RepeatedClass.Rclist));
  /// <summary>
  /// 如果repeated是RcDict，指定Key的类型
  /// </summary>
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::RcDictKey> SoRcdictKeyType =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::RcDictKey>(50003, pb::FieldCodec.ForEnum(400024, x => (int) x, x => (global::RcDictKey) x, global::RcDictKey.Int));
  /// <summary>
  /// 如果repeated是RcDict，元素必须是Message，且要指定Key是值Message的哪一个字段
  /// </summary>
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> SoRcdictKeyName =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(50004, pb::FieldCodec.ForString(400034, ""));
  /// <summary>
  /// map对应的C#类
  /// </summary>
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::MapClass> SoMapClass =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::MapClass>(50005, pb::FieldCodec.ForEnum(400040, x => (int) x, x => (global::MapClass) x, global::MapClass.McDict));
  /// <summary>
  /// 自定义字段，不生成代码；需要手动写序列化和反序列化
  /// </summary>
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> SoCustomField =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(50006, pb::FieldCodec.ForBool(400048, false));
}

#region Enums
/// <summary>
/// 指定repeated对应的类
/// </summary>
public enum RepeatedClass {
  /// <summary>
  /// 列表(默认)
  /// </summary>
  [pbr::OriginalName("RCList")] Rclist = 0,
  /// <summary>
  /// 哈希集
  /// </summary>
  [pbr::OriginalName("RcHashSet")] RcHashSet = 1,
  /// <summary>
  /// 字典
  /// </summary>
  [pbr::OriginalName("RcDict")] RcDict = 2,
}

/// <summary>
/// 指定RcDict的Key类型
/// </summary>
public enum RcDictKey {
  /// <summary>
  /// int
  /// </summary>
  [pbr::OriginalName("RcDictKeyInt")] Int = 0,
  /// <summary>
  /// long
  /// </summary>
  [pbr::OriginalName("RcDictKeyLong")] Long = 1,
  /// <summary>
  /// string
  /// </summary>
  [pbr::OriginalName("RcDictKeyString")] String = 2,
  /// <summary>
  /// Type：Value消息里面必须是oneof
  /// </summary>
  [pbr::OriginalName("RcDictKeyType")] Type = 3,
}

/// <summary>
/// 指定map对应的类
/// </summary>
public enum MapClass {
  /// <summary>
  /// 字典(默认)
  /// </summary>
  [pbr::OriginalName("McDict")] McDict = 0,
}

#endregion


#endregion Designer generated code
